c_stdlib_version:  # [unix]
  - 10.15          # [osx and x86_64]

MACOSX_SDK_VERSION:         # [osx]
  - 13.3                    # [osx]

channel_targets:
  - conda-forge main
  - conda-forge pytorch_rc
is_rc:
  - False
  - True
zip_keys:
  -
    - channel_targets
    - is_rc

blas_impl:
  - mkl                         # [x86_64]
  # deprioritized on windows, would be nice to have
  - generic                     # [unix]

# GPU builds need GPU agents for testing, but since that's a very rare resource,
# we want to build CPU builds on CPU agents at least
# https://github.com/conda-forge/.cirun
github_actions_labels:          # [linux or win]
- cirun-openstack-cpu-2xlarge   # [linux]
- cirun-openstack-gpu-2xlarge   # [linux]
- cirun-openstack-gpu-2xlarge   # [linux]
- cirun-azure-windows-2xlarge   # [win]

megabuild:
- true      # [linux]
- false     # [osx]
- true      # [win]
